import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/bin-encode-decode": 'structure',
  "/china-identification-card": 'structure',
  "/chunkify": 'structure',
  "/clonelicious": 'structure',
  "/cloud-file-storage": 'structure',
  "/color-output": 'structure',
  "/compare-version": 'structure',
  "/development-standards": 'structure',
  "/file-operation": 'structure',
  "/future-fn": 'structure',
  "/gtl": 'structure',
  "/http-compress": 'structure',
  "/http-constant": 'structure',
  "/http-request": 'structure',
  "/http-type": 'structure',
  "/hyperlane": 'structure',
  "/hyperlane-broadcast": 'structure',
  "/hyperlane-log": 'structure',
  "/hyperlane-time": 'structure',
  "/lombok-macros": 'structure',
  "/ltpp": 'structure',
  "/ltpp-code-run": 'structure',
  "/ltpp-event-publish-subscribe-in-javascript": 'structure',
  "/ltpp-gitlab": 'structure',
  "/ltpp-html-pdf": 'structure',
  "/ltpp-leetcode-and-acwing-rank": 'structure',
  "/ltpp-oj-judge-testdata-creat": 'structure',
  "/ltpp-post-blog-user-crawler": 'structure',
  "/ltpp-qrcode": 'structure',
  "/ltpp-rust-get-proxy-request": 'structure',
  "/ltpp-rust-web-server": 'structure',
  "/ltpp-share": 'structure',
  "/ltpp-sqs-douyin-collection-download": 'structure',
  "/ltpp-ssh": 'structure',
  "/ltpp-web-ide": 'structure',
  "/recoverable-spawn": 'structure',
  "/recoverable-thread-pool": 'structure',
  "/server-manager": 'structure',
  "/std-macro-extensions": 'structure',
  "/tcp-request": 'structure',
  "/tcplane": 'structure',
  "/udp": 'structure',
  "/udp-request": 'structure',
});